services:
  database:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=admin123
    volumes:
      - index-data:/data
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - ADMIN=admin
      - ADMIN_PASS=admin123
      - PORT=8080
      - DATABASE_URL=http://database:4080
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  index-data:
